
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP}  # список брокеров
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1
    consumer:
      # group-id: vacancy-service
      auto-offset-reset: earliest